# Generated by Django 4.2.3 on 2023-07-29 14:01

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="age",
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=phone_field.models.PhoneField(blank=True, help_text="Contact phone number", max_length=31),
        ),
    ]
