# Generated by Django 4.2.3 on 2023-07-29 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_contact_options_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["name", "phone", "created_at"]},
        ),
    ]
