# Generated by Django 4.2.3 on 2023-07-29 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["id", "name", "phone", "created_at", "modified_at"]},
        ),
    ]
